"""Changed everything that touches to player id to BigInteger.

Revision ID: 2757518b534a
Revises: 2b1cf8b1d855
Create Date: 2012-06-27 04:54:49.869122

"""

# revision identifiers, used by Alembic.
revision = '2757518b534a'
down_revision = '2b1cf8b1d855'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('joins', 'player_id', type_=sa.BigInteger)
    op.alter_column('messages', 'player_id', type_=sa.BigInteger)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('joins', 'player_id', type_=sa.Integer)
    op.alter_column('messages', 'player_id', type_=sa.Integer)
    ### end Alembic commands ###
