"""Changed the side attribute of joins to spot.

Revision ID: 27c0ca36e0de
Revises: 1fcf103516a8
Create Date: 2012-08-10 10:48:32.835094

"""

# revision identifiers, used by Alembic.
revision = '27c0ca36e0de'
down_revision = '1fcf103516a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('joins', sa.Column('spot', sa.Integer(), nullable=True))
    op.drop_column('joins', u'side')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('joins', sa.Column(u'side', sa.INTEGER(), nullable=True))
    op.drop_column('joins', 'spot')
    ### end Alembic commands ###
