"""Changed the data type of Player.id to BigInteger.

Revision ID: 2b1cf8b1d855
Revises: 3acb1d5a4006
Create Date: 2012-06-27 04:35:33.267457

"""

# revision identifiers, used by Alembic.
revision = '2b1cf8b1d855'
down_revision = '3acb1d5a4006'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'id', type_=sa.BigInteger)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'id', type_=sa.Integer)
    ### end Alembic commands ###
