"""Added a field to the Join model.

Revision ID: 3acb1d5a4006
Revises: 43ca03a53294
Create Date: 2012-06-26 20:12:49.583348

"""

# revision identifiers, used by Alembic.
revision = '3acb1d5a4006'
down_revision = '43ca03a53294'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('joins', sa.Column('side', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('joins', 'side')
    ### end Alembic commands ###
