"""Added a column to notifications, 'side'.

Revision ID: 66c383cb0ab
Revises: 5240e406ddaa
Create Date: 2012-06-27 11:19:12.105185

"""

# revision identifiers, used by Alembic.
revision = '66c383cb0ab'
down_revision = '5240e406ddaa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('side', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'side')
    ### end Alembic commands ###
